### ISSUE TITLE
segfault after upgrading to 5fd779d91f56fff1cd7dd2ef230010543c0c790a

### ISSUE THREAD

**Issue by uscanner** [Tencent/rapidjson#1236]
Code had been working fine for several years, holding up well even against garbage input. After upgrading to 5fd779d91f56fff1cd7dd2ef230010543c0c790a, we got the following SEGFAULT when feeding it garbage input.

It appears that while iterating through members, the member iterator gets to the point where it internally holds a NULL pointer, and as soon as the -> operator gets applied during the next iteration, rapidjson crashes.

Program terminated with signal **SIGSEGV**, Segmentation fault.
(gdb)  bt    
#0  rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::StringEqual
<rapidjson::MemoryPoolAllocator<> > (rhs=..., this=0x7fbe068097b0)                                                       
    at rapidjson/include/rapidjson/document.h:2101                                                
#1  rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::FindMember<
rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > (this=0x7fbe05fffcc0, name=...)                                
    at rapidjson/include/rapidjson/document.h:1257                                                
#2  0x00007fbe57968d76 in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAll
ocator> >::FindMember (this=0x7fbe05fffcc0, name=0x7fbe57970b65 "id")                                                    
    at rapidjson/include/rapidjson/document.h:1233                                                
#3  rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::FindMember 
(name=0x7fbe57970b65 "id", this=0x7fbe05fffcc0) at rapidjson/include/rapidjson/document.h:1236    
#4  rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::HasMember  
    (name=0x7fbe57970b65 "id", this=0x7fbe05fffcc0)                                                                      
    at rapidjson/include/rapidjson/document.h:1193                                                
#5  ParseMessage ()                                                        
    at parse.cpp:41
(gdb) frame 5                                                                                                            
#5  ParseMessage ()                                                        
    at parse.cpp:41                  
41          if (!doc.HasMember("id")) {                                                                              
(gdb) frame 1                                                                                                            
#1  rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::FindMember<
rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > (this=0x7fbe05fffcc0, name=...)                                
    at rapidjson/include/rapidjson/document.h:1257                                                
1257                if (name.StringEqual(member->name))                                                                  
(gdb) l                                                                                                                  
1252        MemberIterator FindMember(const GenericValue<Encoding, SourceAllocator>& name) {                             
1253            RAPIDJSON_ASSERT(IsObject());                                                                            
1254            RAPIDJSON_ASSERT(name.IsString());                                                                       
1255            MemberIterator member = MemberBegin();                                                                   
1256            for ( ; member != MemberEnd(); ++member)                                                                 
1257                if (name.StringEqual(member->name))                                                                  
1258                    break;                                                                                           
1259            return member;                                                                                           
1260        }                                                                                                            
1261        template <typename SourceAllocator> ConstMemberIterator FindMember(const GenericValue<Encoding, SourceAllocat
or>& name) const { return const_cast<GenericValue&>(*this).FindMember(name); }                                           
(gdb) p *this                                                                                                            
$32 = {static kDefaultArrayCapacity = <optimized out>, static kDefaultObjectCapacity = <optimized out>, data_ = {s = {   
      length = 9, hashcode = 0, str = 0x1f6000000000000 <error: Cannot access memory at address 0x1f6000000000000>},     
    ss = {str = "\t", '\000' <repeats 12 times>}, n = {i = {i = 9, padding = "\000\000\000"}, u = {u = 9,                
        padding2 = "\000\000\000"}, i64 = 9, u64 = 9, d = 4.4465908125712189e-323}, o = {size = 9, capacity = 0,         
      members = 0x1f6000000000000}, a = {size = 9, capacity = 0, elements = 0x1f6000000000000}, f = {                    
      payload = "\t", '\000' <repeats 12 times>, flags = 502}}}                                                          
(gdb) p **member**                                                                                                           
$33 = {ptr_ = **0x0**}                                                                                                       
(gdb)

**Comment by uscanner** [comment]
I just noticed that this is potentially the same issue as #1212.

**Comment by miloyip** [comment]
I think it may due to inproper usage and the undesired behavior depends on the memory allocation pattern. Such as accessing a value in an already destructed document. Can you show a bit of code?

**Comment by uscanner** [comment]
I haven't been able to reproduce with a small amount of code and some hand-crafted input... But these are the asserts (logged but disabled) leading to each segfault. I am pasting four asserts for each process, 5 crashes total.

I am pasting them here hoping they can provide a useful hint.

include/rapidjson/document.h:1162:  (11200) Thu May  3 02:58:28 2018 rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberEnd() const [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator = rapidjson::GenericMemberIterator<true, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1253:  (11200) Thu May  3 02:58:28 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::FindMember(const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1165:  (11200) Thu May  3 02:58:28 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberBegin() [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1168:  (11200) Thu May  3 02:58:28 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberEnd() [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1162:  (25391) Thu May  3 02:59:49 2018 rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberEnd() const [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator = rapidjson::GenericMemberIterator<true, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1253:  (25391) Thu May  3 02:59:49 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::FindMember(const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1165:  (25391) Thu May  3 02:59:49 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberBegin() [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1168:  (25391) Thu May  3 02:59:49 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberEnd() [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1162:  (35444) Thu May  3 03:12:58 2018 rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberEnd() const [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator = rapidjson::GenericMemberIterator<true, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1253:  (35444) Thu May  3 03:12:58 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::FindMember(const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1165:  (35444) Thu May  3 03:12:58 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberBegin() [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1168:  (35444) Thu May  3 03:12:58 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberEnd() [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1162:  (12681) Thu May  3 03:14:16 2018 rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberEnd() const [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator = rapidjson::GenericMemberIterator<true, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1253:  (12681) Thu May  3 03:14:16 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::FindMember(const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1165:  (12681) Thu May  3 03:14:16 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberBegin() [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1168:  (12681) Thu May  3 03:14:16 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberEnd() [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1162:  (23049) Thu May  3 03:15:25 2018 rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberEnd() const [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator = rapidjson::GenericMemberIterator<true, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1253:  (23049) Thu May  3 03:15:25 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::FindMember(const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1165:  (23049) Thu May  3 03:15:25 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberBegin() [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"
include/rapidjson/document.h:1168:  (23049) Thu May  3 03:15:25 2018 rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberEnd() [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]  "IsObject()"

**Comment by uscanner** [comment]
Do you still need a snippet of code to reproduce this? I bet it would suffice to have some number, which would parse as some legal json value. Then look for some member with HasMember('xyz') and that most likely would reproduce it.

**Comment by miloyip** [comment]
If it has assertion fail, I think it is probably due to incorrect call. For example, `v.HasMember(...)` is only valid if `v.IsObject()`.

**Comment by sandr8** [comment]
Shouldn't it gracefully return false in final images?

This was gracefully failing in older versions of rapidjson.

**Comment by OliCoder** [comment]
Our team got the same SEGFAULT while using rapidjson in at least two projects, it finally cores while xx.StringEqual() calling memcmp(), so I think it is probably due to NULL pointer.

**Comment by zengzhenbo** [comment]
Our team got the same SEGFAULT，and the doc is array，invalid for our business，use the same array data for test, but can't reproduce segfault.
Maybe we should call `IsObject()` before `FindMember()`/`HasMember()`

`#0  0x00007f57d8d5adea in __memcmp_sse4_1 () from /lib64/libc.so.6
#1  0x0000000000751623 in StringEqual<rapidjson::MemoryPoolAllocator<> > (rhs=..., this=<synthetic pointer>) at /path/commlib/src/include/rapidjson/document.h:1750
#2  FindMember<rapidjson::MemoryPoolAllocator<> > (name=<synthetic pointer>, this=0x7f565affc950) at /path/commlib/src/include/rapidjson/document.h:965
#3  rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::FindMember (this=this@entry=0x7f565affc950, name=name@entry=0xa5d25d "statuses")
    at /path/commlib/src/include/rapidjson/document.h:941
#4  0x00000000007496b7 in XpnsReport::Server::processData (this=this@entry=0x7ffe0cd6acf0, 
    data="[{...},{...},{...}]", 
    ackNode=std::shared_ptr (count 1, weak 0) 0x7f5640000b68) at /path/src/Server.cpp:682`
