### ISSUE TITLE
Stack exhausted when parsing malformed json file

### ISSUE THREAD

**Issue by maverick117** [Tencent/rapidjson#1392]
Program:
```
#include "rapidjson/reader.h"
#include <iostream>

using namespace rapidjson;
using namespace std;

struct MyHandler {
    bool Null() { cout << "Null()" << endl; return true; }
    bool Bool(bool b) { cout << "Bool(" << boolalpha << b << ")" << endl; return true; }
    bool Int(int i) { cout << "Int(" << i << ")" << endl; return true; }
    bool Uint(unsigned u) { cout << "Uint(" << u << ")" << endl; return true; }
    bool Int64(int64_t i) { cout << "Int64(" << i << ")" << endl; return true; }
    bool Uint64(uint64_t u) { cout << "Uint64(" << u << ")" << endl; return true; }
    bool Double(double d) { cout << "Double(" << d << ")" << endl; return true; }
    bool RawNumber(const char* str, SizeType length, bool copy) { 
        cout << "Number(" << str << ", " << length << ", " << boolalpha << copy << ")" << endl;
        return true;
    }
    bool String(const char* str, SizeType length, bool copy) { 
        cout << "String(" << str << ", " << length << ", " << boolalpha << copy << ")" << endl;
        return true;
    }
    bool StartObject() { cout << "StartObject()" << endl; return true; }
    bool Key(const char* str, SizeType length, bool copy) {
        cout << "Key(" << str << ", " << length << ", " << boolalpha << copy << ")" << endl;
        return true;
    }
    bool EndObject(SizeType memberCount) { cout << "EndObject(" << memberCount << ")" << endl; return true; }
    bool StartArray() { cout << "StartArray()" << endl; return true; }
    bool EndArray(SizeType elementCount) { cout << "EndArray(" << elementCount << ")" << endl; return true; }
};

int main() {
    string s;
    cin >> s;

    MyHandler handler;
    Reader reader;
    reader.Parse(s, handler);

    return 0;
}
```

A malformed input such as one generated by 
```$ for i in `seq 0 60000`; do printf '[[[[[['; done```
will result in a segmentation fault, given the input is large enough.

Our test environment is a Debian (Buster) server with 24 cores and 256GiB of RAM, but we believe that the result would be the same regardless of operating systems or hardware configuration.

We dumped the stack backtrace using gdb:
```
#0  0x0000000000415cc8 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1392
#1  0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#2  0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#3  0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#4  0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#5  0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#6  0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#7  0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#8  0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#9  0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#10 0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#11 0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#12 0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#13 0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#14 0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#15 0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#16 0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#17 0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#18 0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#19 0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#20 0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#21 0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#22 0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#23 0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#24 0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#25 0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#26 0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#27 0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
#28 0x0000000000415d59 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:1399
#29 0x0000000000418c29 in rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<0u, rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> > (this=0x7fffffffe0d0, is=..., handler=...) at cpp3rdlib/rapidjson/include/rapidjson/reader.h:674
...
```

The stack backtrace identifies the error as stack exhaustion, since RapidJSON recursively calls ```ParseValue()```, thus allocating too many stack frames. If the ```Parse()``` function is exposed to the public, this could result in Denial of Service attacks.

Some json serialization/deserialization libraries such as ```serde_json``` in Rust adds runtime checks to ensure the stack depth does not exceed a certain amount and returns an enum value, indicating either success or failure, allowing for graceful handling of these errors.

**Comment by miloyip** [comment]
`kParseIterativeFlag` can prevent this problem.

**Comment by miloyip** [comment]
BTW, since you are using `Reader` API, you may also add counter in `StartObject()`, `StartArray`, `EndObject()`, `EndArray` to measure the depth. And return `false` to terminate the parsing process.
