### ISSUE TITLE
Realloc of a null stack pointer leads to unexpected behavior on arm

### ISSUE THREAD

**Issue by badiozam** [Tencent/rapidjson#1407]
```
#0  rapidjson::CrtAllocator::Realloc (this=0x2840f90, originalPtr=0x0, originalSize=0, newSize=256) at inc/rapidjson/allocators.h:73
#1  0x0216bc40 in rapidjson::internal::Stack<rapidjson::CrtAllocator>::Resize (this=0xbefff0c0, newCapacity=256) at inc/rapidjson/internal/stack.h:202
#2  0x0216bcd2 in rapidjson::internal::Stack<rapidjson::CrtAllocator>::Expand<rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0u>::Level> (this=0xbefff0c0, count=1) at inc/rapidjson/internal/stack.h:197
#3  0x0216b716 in rapidjson::internal::Stack<rapidjson::CrtAllocator>::Reserve<rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0u>::Level> (this=0xbefff0c0, count=1) at inc/rapidjson/internal/stack.h:118
#4  0x0216b14e in rapidjson::internal::Stack<rapidjson::CrtAllocator>::Push<rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0u>::Level> (this=0xbefff0c0, count=1) at inc/rapidjson/internal/stack.h:123
#5  0x0216aa0c in rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0u>::StartObject (this=0xbefff0bc) at inc/rapidjson/writer.h:219
```

The C++ docs say the pointer passed to std::realloc must've been previously allocated (by malloc, calloc or realloc). The memory pool allocator seems to already have this check. I propose adding it to the C runtime allocator wrapper as well:

```C++
    void* Realloc(void* originalPtr, size_t originalSize, size_t newSize) {
        if (originalPtr == 0)
            return Malloc(newSize);
    
        (void)originalSize;
        if (newSize == 0) {
            std::free(originalPtr);
            return NULL;
        }

        return std::realloc(originalPtr, newSize);
    }
```
in allocator.h starting at line 71

**Comment by miloyip** [comment]
But in https://en.cppreference.com/w/cpp/memory/c/realloc

> If ptr is a null pointer, the behavior is the same as calling std::malloc(new_size).

**Comment by badiozam** [comment]
I stand corrected! I must have another memory bug somewhere else in my code.
