### ISSUE TITLE
Document 调用Accept崩溃问题

### ISSUE THREAD

**Issue by wssbygone** [Tencent/rapidjson#1828]
使用Document Accept就崩溃，是否是json对象太大导致的？？
调用栈如下：

#0  0x00007ffb59d97337 in raise () from /lib64/libc.so.6
#1  0x00007ffb59d98a28 in abort () from /lib64/libc.so.6
#2  0x00007ffb59d90156 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffb59d90202 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000000417a0b in rapidjson::internal::Stack<rapidjson::CrtAllocator>::PushUnsafe<char> (this=0x7ffc46364a40, count=1)
    at RawData/../include/rapidjson/internal/stack.h:130
#5  0x0000000000425e1a in rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>::PutUnsafe (
    this=0x7ffc46364a40, c=68 'D') at include/rapidjson/stringbuffer.h:57
#6  0x00000000004258fd in rapidjson::PutUnsafe<rapidjson::UTF8<char>, rapidjson::CrtAllocator> (stream=..., c=68 'D')
    at include/rapidjson/stringbuffer.h:106
#7  0x0000000000426cdb in rapidjson::Transcoder<rapidjson::UTF8<char>, rapidjson::UTF8<char> >::TranscodeUnsafe<rapidjson::GenericStringStream<rapidjson::UTF8<char> >, rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator> > (is=...,
    os=...) at include/rapidjson/encodings.h:700
#8  0x0000000000426af9 in rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0u>::WriteString (this=0x7ffc46364a70,
    str=0x7ffb2616e028 "data:application/octet-stream;base64,AAAAAAAAtcMAAA9DAABUwwAAFsMAAA9DAABUwwAAFsMAAKBAAAAAAAAAtcMAAABAAAAAAAAAeEIAAA9DAABUQwAAFsMAAA9DAABUQwAAFsM", 'A' <repeats 13 times>, "eEIAAABAAABUQwAAFsMAAAAAAABUQwAAFsMAAA9DAAA"..., length=779789389)
    at include/rapidjson/writer.h:441
#9  0x0000000000426259 in rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0u>::String (this=0x7ffc46364a70,
    str=0x7ffb2616e028 "data:application/octet-stream;base64,AAAAAAAAtcMAAA9DAABUwwAAFsMAAA9DAABUwwAAFsMAAKBAAAAAAAAAtcMAAABAAAAAAAAAeEIAAA9DAABUQwAAFsMAAA9DAABUQwAAFsM", 'A' <repeats 13 times>, "eEIAAABAAABUQwAAFsMAAAAAAABUQwAAFsMAAA9DAAA"..., length=779789389,
    copy=true) at include/rapidjson/writer.h:206
#10 0x0000000000425c85 in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Accept<rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0u> > (this=0x77eb64b8, handler=...)
    at include/rapidjson/document.h:1891
#11 0x0000000000425b3f in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Accept<rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0u> > (this=0x77ec18a8, handler=...)
    at include/rapidjson/document.h:1877
#12 0x0000000000425bef in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Accept<rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0u> > (this=0xbf0578, handler=...) at include/rapidjson/document.h:1886
#13 0x0000000000425b3f in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Accept<rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::CrtAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator, 0u> > (this=0xb01d10, handler=...) at include/rapidjson/document.h:1877

**Comment by OneEightFourThree** [comment]
这个问题有结论吗？我最近也遇到了这个问题，而且是偶发性的。
