### ISSUE TITLE
Schema.TestSuite UndefinedBehaviorSanitizer: undefined-behavior

### ISSUE THREAD

**Issue by hcoona** [Tencent/rapidjson#2020]
```c++
PointerType schemaRef = GetInvalidSchemaPointer().Append(SchemaType::GetValidateErrorKeyword(kValidateErrorDependencies), &GetInvalidSchemaPointer().GetAllocator());
```

The allocator here could be `nullptr` while `GetAllocator()` must return a reference.

```c++
//! Get the allocator of this pointer.
Allocator& GetAllocator() { return *allocator_; }
```

Reproduce steps:

```bash
git clone https://github.com/Tencent/rapidjson.git && cd rapidjson
git checkout fcb23c2dbf561ec0798529be4f66394d3e4996d8 && git submodule update --init --force
mkdir build && cd build
cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug -DRAPIDJSON_BUILD_THIRDPARTY_GTEST=ON -DRAPIDJSON_BUILD_CXX17=ON -DRAPIDJSON_BUILD_ASAN=ON -DRAPIDJSON_BUILD_UBSAN=ON -DRAPIDJSON_ENABLE_INSTRUMENTATION_OPT=OFF -DRAPIDJSON_HAS_STDSTRING=ON -DRAPIDJSON_USE_MEMBERSMAP=ON -DRAPIDJSON_BUILD_DOC=OFF -DRAPIDJSON_BUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=$PWD/output
ninja unittest
UBSAN_OPTIONS=halt_on_error=true:print_stacktrace=1 bin/unittest --gtest_filter=Schema.TestSuite
```

Error reporting:

```text
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Schema
[ RUN      ] Schema.TestSuite
../include/rapidjson/pointer.h:350:41: runtime error: reference binding to null pointer of type 'struct CrtAllocator'
    #0 0x5637cbb16449 in rapidjson::GenericPointer<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >, rapidjson::CrtAllocator>::GetAllocator() ../include/rapidjson/pointer.h:350
    #1 0x5637cbb10fb9 in rapidjson::GenericSchemaValidator<rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >, rapidjson::CrtAllocator>, rapidjson::BaseReaderHandler<rapidjson::UTF8<char>, void>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::EndMissingDependentProperties(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::CrtAllocator> const&) ../include/rapidjson/schema.h:2261
    #2 0x5637cbac3e73 in rapidjson::internal::Schema<rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >, rapidjson::CrtAllocator> >::EndObject(rapidjson::internal::SchemaValidationContext<rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >, rapidjson::CrtAllocator> >&, unsigned int) const ../include/rapidjson/schema.h:1037
    #3 0x5637cba94034 in rapidjson::GenericSchemaValidator<rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >, rapidjson::CrtAllocator>, rapidjson::BaseReaderHandler<rapidjson::UTF8<char>, void>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::EndObject(unsigned int) ../include/rapidjson/schema.h:2411
    #4 0x5637cba78918 in bool rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Accept<rapidjson::GenericSchemaValidator<rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >, rapidjson::CrtAllocator>, rapidjson::BaseReaderHandler<rapidjson::UTF8<char>, void>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > >(rapidjson::GenericSchemaValidator<rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >, rapidjson::CrtAllocator>, rapidjson::BaseReaderHandler<rapidjson::UTF8<char>, void>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >&) const (/home/shuaiz/GitEnlistments/github.com/public/rapidjson/build/bin/perftest+0x643918)
    #5 0x5637cba6c15c in Schema_TestSuite_Test::TestBody() ../test/perftest/schematest.cpp:211
    #6 0x5637cbbf5ee1 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ../thirdparty/gtest/googletest/src/gtest.cc:2418
    #7 0x5637cbbd70b2 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ../thirdparty/gtest/googletest/src/gtest.cc:2454
    #8 0x5637cbb3a239 in testing::Test::Run() ../thirdparty/gtest/googletest/src/gtest.cc:2492
    #9 0x5637cbb3d865 in testing::TestInfo::Run() ../thirdparty/gtest/googletest/src/gtest.cc:2668
    #10 0x5637cbb408e6 in testing::TestCase::Run() ../thirdparty/gtest/googletest/src/gtest.cc:2786
    #11 0x5637cbb7567f in testing::internal::UnitTestImpl::RunAllTests() ../thirdparty/gtest/googletest/src/gtest.cc:5048
    #12 0x5637cbbfc3c5 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ../thirdparty/gtest/googletest/src/gtest.cc:2418
    #13 0x5637cbbdc4b2 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ../thirdparty/gtest/googletest/src/gtest.cc:2454
    #14 0x5637cbb6989f in testing::UnitTest::Run() ../thirdparty/gtest/googletest/src/gtest.cc:4664
    #15 0x5637cb9605be in RUN_ALL_TESTS() ../thirdparty/gtest/googletest/include/gtest/gtest.h:2329
    #16 0x5637cb9603a5 in main ../test/perftest/perftest.cpp:23
    #17 0x7fc794cec0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #18 0x5637cb96017d in _start (/home/shuaiz/GitEnlistments/github.com/public/rapidjson/build/bin/perftest+0x52b17d)
```

**Comment by xhon-pelushi** [comment]
Confirmed on current `master` (`24b5e7a`), and I think this one has a satisfying answer: **the allocator argument that causes it has been obsolete since June 2021, so the fix is a deletion.**

## Minimal reproduction

No need for the whole `Schema.TestSuite` — three lines of schema and document are enough, and it fires with **default validation flags**, not just when reporting all errors:

```cpp
Document sd; sd.Parse("{\"dependencies\": {\"a\": [\"b\", \"c\"]}}");
SchemaDocument schema(sd);
Document d;  d.Parse("{\"a\": 1}");     // "a" present, dependents missing
SchemaValidator v(schema);
d.Accept(v);
```

```
include/rapidjson/pointer.h:344:40: runtime error: reference binding to null pointer of type 'rapidjson::CrtAllocator'
    #0 GenericPointer<...>::GetAllocator()                       pointer.h:344:33
    #1 GenericSchemaValidator<...>::EndMissingDependentProperties(...)  schema.h:2706:162
    #2 internal::Schema<...>::EndObject(...)                     schema.h:1189:47
    #3 GenericSchemaValidator<...>::EndObject(...)               schema.h:2867:30
```

Your diagnosis is exactly right. `GetInvalidSchemaPointer()` is

```cpp
PointerType GetInvalidSchemaPointer() const {
    return schemaStack_.Empty() ? PointerType() : CurrentSchema().GetPointer();
}
```

and `PointerType()` is the default constructor, which leaves `allocator_` null. `GetAllocator()` then does `return *allocator_` unconditionally.

## Why the argument is there, and why it no longer needs to be

The `&GetInvalidSchemaPointer().GetAllocator()` argument came from #1805. In that issue the author tried three options for this exact call site and reported:

> 2. If I do **not** pass an allocator, all unit tests pass on Linux & Mac, but the `TestSuite` unit test fails on Windows … `SEH exception with code 0xc0000005`, an access violation.
> 3. If `<alloc>` is the pointer's allocator obtained via its `&GetInvalidSchemaPointer().GetAllocator()` method then all unit & perf tests pass.

Option 3 shipped, and the comment *"When appending to a pointer ensure its allocator is used"* is its residue.

But the reason option 2 crashed was a separate bug in `GenericPointer`, and it was fixed properly by **#1904** (merged 2021-06-14, *"Fix Pointer::Append() crash for custom allocator on Windows"*):

```diff
-    GenericPointer(const GenericPointer& rhs) : allocator_(rhs.allocator_), ...
+    GenericPointer(const GenericPointer& rhs) : allocator_(), ...
```

with the PR description noting *"the `return` may call copy constructor, which incorrectly using the source's allocator. This cause problem because the source is temporary and will be destructed."* Since then a copied pointer creates its **own** allocator — `Pointer.CopyConstructor` even asserts `EXPECT_NE(&p.GetAllocator(), &q.GetAllocator())` — which is precisely the property option 2 needed.

So the workaround has been unnecessary for four years, and it is now the only thing producing this UB.

## The fix

```diff
-            // When appending to a pointer ensure its allocator is used
-            PointerType schemaRef = GetInvalidSchemaPointer().Append(SchemaType::GetValidateErrorKeyword(kValidateErrorDependencies), &GetInvalidSchemaPointer().GetAllocator());
-            AddErrorSchemaLocation(error, schemaRef.Append(sourceName.GetString(), sourceName.GetStringLength(), &GetInvalidSchemaPointer().GetAllocator()));
+            // Append() gives the returned pointer its own allocator (see #1904),
+            // so no allocator needs to be threaded through here. Passing
+            // &GetInvalidSchemaPointer().GetAllocator() is undefined when the
+            // pointer has no allocator, which is the case whenever the schema
+            // stack is empty.
+            PointerType schemaRef = GetInvalidSchemaPointer().Append(SchemaType::GetValidateErrorKeyword(kValidateErrorDependencies));
+            AddErrorSchemaLocation(error, schemaRef.Append(sourceName.GetString(), sourceName.GetStringLength()));
```

Verified by building the whole unit suite with clang `-fsanitize=address,undefined`:

| | tests | UBSan diagnostics |
| --- | --- | --- |
| `master` | 468 / 468 pass | **2** — `pointer.h:344` for both `CrtAllocator` and `MemoryPoolAllocator<>`, from `SchemaValidator.Object_PropertyDependencies` and `SchemaValidator.TestSuite` |
| with the patch | 468 / 468 pass | **0** |

The important part is that the reported error is unchanged. I diffed the serialised error object before and after for both a top-level `dependencies` violation and a nested one, and they are byte-identical — in particular the schema location is still

```
"schemaRef": "#/properties/inner/dependencies/first"
```

which is what #1835/#1837 introduced this code to get right.

There is a second, currently-harmless problem at the same call site worth mentioning while it's open: `GetInvalidSchemaPointer()` returns **by value**, so `&GetInvalidSchemaPointer().GetAllocator()` takes the address of an allocator owned by a temporary that dies at the end of the full expression. Today `schemaRef.allocator_` is left dangling but never dereferenced — `Append()` uses the allocator passed to it, and the destructor's `Allocator::Free` is static — so nothing goes wrong. Removing the argument removes that hazard too.

## Possibly the same root cause as #2298

#2298 reports Valgrind `Invalid read of size 4` inside `GenericPointer::CopyFromRaw`, **only when the schema uses `dependencies`** — the same feature and the same call site. A dangling allocator here would land exactly in `CopyFromRaw`, which is the one place that dereferences it (`allocator_->Malloc(...)`).

I could not reproduce that invalid read on current `master`, with either a top-level or a nested `dependencies` schema, so I can't claim they're the same bug — only that they share a call site and that this patch removes the mechanism that would explain it. Might be worth asking that reporter to re-test with this change.

## What I have not tested

Linux, clang 18 and GCC 13, x86-64. I have no MSVC/Windows build, which is exactly the configuration where option 2 originally failed in #1805. #1904's fix is a constructor change rather than anything compiler-specific, and the copy-constructor test asserts the property option 2 depends on, so I'd expect it to hold — but given the history, someone with Windows CI confirming `Schema.TestSuite` and `jsonschema/tests/draft4/dependencies.json` would be worth having before this lands.

Happy to open a PR with the change and a regression test if that's useful.
