### ISSUE TITLE
JSON Schema `oneOf` does not respect `const` as a discriminator

### ISSUE THREAD

**Issue by evanpurkhiser** [Tencent/rapidjson#2314]
Given the schema

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "oneOf": [
    {
      "$ref": "#/definitions/First"
    },
    {
      "$ref": "#/definitions/Second"
    }
  ],
  "definitions": {
    "First": {
      "type": "object",
      "properties": {
        "type":  {"const": "one"},
        "value": {"type": "number"}
      },
      "required": ["type", "value"]
    },
    "Second": {
      "type": "object",
      "properties": {
        "type":  {"const": "two"},
        "value": {"type": "number"}
      },
      "required": ["type", "value"]
    }
  }
}
```

I would expect these two schemas to be seen as different shapes and should correctly match these two examples

```json
{"type": "one", "value": 5}
```

```json
{"type": "two", "value": 5}
```

And for this to be invald
```json
{"type": "three", "value": 5}
```

Using the python-rapidjson library:

```python
>>> import rapidjson
>>> compiled = rapidjson.Validator(open('example.schema.json').read())
>>> compiled('{"type": "one", "value": 5}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
rapidjson.ValidationError: ('oneOf', '#', '#')
>>> compiled('{"type": "two", "value": 5}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
rapidjson.ValidationError: ('oneOf', '#', '#')
>>> compiled('{"type": "three", "value": 5}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
rapidjson.ValidationError: ('oneOf', '#', '#')
```

---

If I change the `type` from using `const` to something like `enum: ["one"]` this works.

I would expect const as a shape discriminator to work.

**Comment by Dich0tomy** [comment]
Honestly thank you for that workaround idea with the enum.

I'll probably switch from rapidjson json schemas at some point because they're in no state to work with, but this buys me some time for a bigger migration.

One additional thing I did to make the errors nicer, from:
```
1. [enum] #/type: Property has a value that is not one of its allowed enumerated values.
```
to
```
1. [const] #/type: Property has a value 'hello' that is not a constant 'f1'.
```
(my own formatting `[{type}] {schemaRef}: {message}`)

was to include a meta field alongside the enum, then crudely intercept it at the stage of parsing errors and replacing the error message:

```cpp
struct PatchedErrorCtx
{
  String name;
  String msg;
};

auto try_patch_error_message(String name, json::CrtValue const& error, json::Value const& input, json::Value const& schema) -> Opt<PatchedErrorCtx>
{
  auto const stringify = [](json::Value const& val) {
    if(val.IsArray()) return fmt::format("<array of size {}>", val.Size());
    else if(val.IsObject()) return fmt::format("<object of size {}>", val.MemberCount());
    else return stringify_value(val);
  };

  auto instance_ptr = json::Pointer(error["instanceRef"].GetString());
  auto schema_ptr = json::Pointer(error["schemaRef"].GetString());
  auto const& value = *instance_ptr.Get(input);
  auto const& constraint = *schema_ptr.Get(schema);

  if(name == "enum") {
    /// We use a `{ "enum": [<single value>], "$const": true }` as a workaround around rapidjson not supporting
    /// anything higher than draft v4.
    if(constraint.HasMember("$const")) {
      return PatchedErrorCtx {
        .name = "const",
        .msg = fmt::format(
          "Property has a value '{}' that is not a constant '{}'.",
          stringify(value),
          stringify(constraint["enum"][0])
        ),
      };
    }
    else {
      return PatchedErrorCtx {
        .name = std::move(name),
        .msg = fmt::format("Property has a value '{}' that is not in the enumeration list.", stringify(value)),
      };
    }
  }

  return {};
}

auto parse_single_error(String error_name, json::CrtValue const& error, json::Value const& input, json::Value const& schema) -> DynArray<SchemaValidationError>
{
  if(error.ObjectEmpty()) return {};

  auto error_msg = String();
  if(auto patched = try_patch_error_message(error_name, error, input, schema)) {
    error_name = std::move(patched->name);
    error_msg = std::move(patched->msg);
  }
  else {
    error_msg = extract_message(error);
  }

  auto out = SchemaValidationError {
    .category = std::move(error_name),
    .message = std::move(error_msg),
    .path = String(error["instanceRef"].GetString(), error["instanceRef"].GetStringLength()),
  };

	// Other error parsing code
}
```
